# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "dayna-codes-deployments"
  EB_APPLICATION_NAME       : "Dayna Codes blog"
  EB_ENVIRONMENT_NAME       : "Daynacodesblog-env-1"
  DEPLOY_PACKAGE_NAME       : "deployment-${{ github.sha }}.zip"
  AWS_REGION                : "us-west-2"
  
# Controls when the workflow will run
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   build:
  my_ci_pipeline:
    runs-on: ubuntu-latest
        
    steps:
      - name: Git clone our repository
        uses: actions/checkout@v1
            
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
#           role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role

      - name: Copy Deployment Package to S3
        run :  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
            
      - name: Print message on completion 
        run:  echo "CI Pipeline part finished successfully"
