name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "dayna-codes-blog-deployments"
  EB_APPLICATION_NAME       : "Dayna Codes blog"
  EB_ENVIRONMENT_NAME       : "Daynacodesblog-env-1"
  DEPLOY_PACKAGE_NAME       : "deployment-${{ github.sha }}.zip"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2
  AWS_DEFAULT_OUTPUT: json
  
on:
  push:
    branches: 
      - main

jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest
        
    steps:
      - name: Git clone our repository
        uses: actions/checkout@v2
            
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: arn:aws:iam::163578322949:role/github-actions-elasticbeanstalk-role
            role-duration-seconds: 900 # the ttl of the session, in seconds.
            aws-region: us-west-2 # use your region here.
      
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           role-to-assume: arn:aws:iam::163578322949:user/github-actions-blog
#           aws-region: us-west-2

#           role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role

      - name: Copy Deployment Package to S3
        run :  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
            
      - name: Print message on completion 
        run:  echo "CI Pipeline part finished successfully"
        
  my_cd_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: arn:aws:iam::163578322949:role/github-actions-elasticbeanstalk-role
            role-duration-seconds: 900 # the ttl of the session, in seconds.
            aws-region: us-west-2 # use your region here.
            
      - name: Create new Beanstalk version
        run : 
          aws elasticbeanstalk create-application-version --application-name "${{ env.EB_APPLICATION_NAME }}" --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" --version-label "Ver-${{ github.sha }}" --description "CommitSHA-${{ github.sha }}"
          
      - name: Deploy new beanstalk version
        run : aws elasticbeanstalk update-environment --environment-name "${{env.EB_ENVIRONMENT_NAME}}" --version-label "Ver-${{github.sha}}"
        
      - name: Print message on completion 
        run:  echo "CD Pipeline part finished successfully"
      
